bind_ip: "127.0.0.1"  # Change this line
sip_port: 5060
rtp_port_start: 20000
rtp_port_end: 30000
max_calls: 200
tcp_target: "127.0.0.1:9000"
codec_preference: ["PCMU", "PCMA"]
mode: "tcp" # can be echo, tcp
recording_mode: true
recording_path: "./recordings"
log_level: "DEBUG"